use lovely python to avoid error
File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
   self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file